apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnetcore-testsvc-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dotnetcore-testsvc-app
  template:
    metadata:
      labels:
        app: dotnetcore-testsvc-app
    spec:
      containers:
        - name: dotnetcore-testsvc-app-image
          image: $CONTAINER_REGISTRY_NAME.azurecr.io/dotnetcore-testsvc-app-image:latest
          imagePullPolicy: "Always"
          env:
            - name: "PORT"
              value: "5000"
